#!/usr/bin/env bash

scripts_base=$(dirname $0)

echo "Installing Packages"
$scripts_base/tmux-deps
echo "Installing neovim dependencies"
$scripts_base/nvim-deps
echo "Installing tmux dependencies"
$scripts_base/tmux-deps
echo "Copying Config"
$scripts_base/sync-config
